# Generated by Django 3.2.7 on 2021-09-15 20:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service_app', '0003_remove_shop_wallet'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shop',
            name='case',
        ),
        migrations.RemoveField(
            model_name='shop',
            name='disc',
        ),
        migrations.RemoveField(
            model_name='shop',
            name='graphic',
        ),
        migrations.RemoveField(
            model_name='shop',
            name='memory',
        ),
        migrations.RemoveField(
            model_name='shop',
            name='motherboard',
        ),
        migrations.RemoveField(
            model_name='shop',
            name='power_supply',
        ),
        migrations.RemoveField(
            model_name='shop',
            name='processor',
        ),
        migrations.RemoveField(
            model_name='shop',
            name='user',
        ),
    ]
