# Generated by Django 3.2.7 on 2021-09-15 20:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('service_app', '0004_auto_20210915_2207'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='case',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='case_shop', to='service_app.motherboard'),
        ),
        migrations.AddField(
            model_name='shop',
            name='disc',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='disc_shop', to='service_app.motherboard'),
        ),
        migrations.AddField(
            model_name='shop',
            name='graphic',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='graphic_shop', to='service_app.motherboard'),
        ),
        migrations.AddField(
            model_name='shop',
            name='memory',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='memory_shop', to='service_app.motherboard'),
        ),
        migrations.AddField(
            model_name='shop',
            name='motherboard',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='motherboard_shop', to='service_app.motherboard'),
        ),
        migrations.AddField(
            model_name='shop',
            name='power_supply',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='power_supply_shop', to='service_app.motherboard'),
        ),
        migrations.AddField(
            model_name='shop',
            name='processor',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='processor_shop', to='service_app.motherboard'),
        ),
        migrations.AddField(
            model_name='shop',
            name='user',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='user_shop', to=settings.AUTH_USER_MODEL),
        ),
    ]
