# Generated by Django 3.2.7 on 2021-09-15 20:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service_app', '0006_auto_20210915_2210'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Shop',
        ),
    ]
