# Generated by Django 3.2.7 on 2021-09-15 20:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('service_app', '0007_delete_shop'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='case_shop', to='service_app.motherboard')),
                ('disc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='disc_shop', to='service_app.motherboard')),
                ('graphic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='graphic_shop', to='service_app.motherboard')),
                ('memory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memory_shop', to='service_app.motherboard')),
                ('motherboard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='motherboard_shop', to='service_app.motherboard')),
                ('power_supply', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='power_supply_shop', to='service_app.motherboard')),
                ('processor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='processor_shop', to='service_app.motherboard')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_shop', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
