# Generated by Django 3.2.7 on 2021-09-17 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_app', '0015_case_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='motherboard',
            name='price',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
