# Generated by Django 3.2.7 on 2021-09-17 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_app', '0018_processor_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='price',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='disc',
            name='price',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='memory',
            name='price',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='powersupply',
            name='price',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
