# Generated by Django 3.2.7 on 2021-09-22 20:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('service_app', '0020_auto_20210917_1305'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disc',
            name='disc_format',
            field=models.CharField(choices=[('m.2', 'M.2'), ('2.5', '2.5'), ('3.5', '3.5')], max_length=5),
        ),
        migrations.AlterField(
            model_name='shop',
            name='case',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='case_shop', to='service_app.case'),
        ),
        migrations.AlterField(
            model_name='shop',
            name='disc',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='disc_shop', to='service_app.disc'),
        ),
        migrations.AlterField(
            model_name='shop',
            name='graphic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='graphic_shop', to='service_app.graphiccard'),
        ),
        migrations.AlterField(
            model_name='shop',
            name='memory',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memory_shop', to='service_app.memory'),
        ),
        migrations.AlterField(
            model_name='shop',
            name='power_supply',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='power_supply_shop', to='service_app.powersupply'),
        ),
        migrations.AlterField(
            model_name='shop',
            name='processor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='processor_shop', to='service_app.processor'),
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='service_app.case')),
                ('disc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='service_app.disc')),
                ('graphic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='service_app.graphiccard')),
                ('memory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='service_app.memory')),
                ('motherboard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='service_app.motherboard')),
                ('power_supply', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='service_app.powersupply')),
                ('processor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='service_app.processor')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
