# Generated by Django 3.2.7 on 2021-09-23 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_app', '0021_auto_20210922_2233'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pc',
            name='price',
            field=models.FloatField(default=0),
        ),
    ]
