# Generated by Django 3.2.7 on 2021-09-23 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_app', '0022_alter_pc_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='powersupply',
            name='format_type',
            field=models.CharField(choices=[('miniATX', 'miniITX'), ('microATX', 'microATX'), ('ATX', 'ATX')], max_length=10),
        ),
    ]
