# Generated by Django 3.2.7 on 2021-09-23 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_app', '0023_alter_powersupply_format_type'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
        migrations.AlterField(
            model_name='case',
            name='price',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='disc',
            name='price',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='graphiccard',
            name='price',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='memory',
            name='price',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='motherboard',
            name='price',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='powersupply',
            name='price',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='processor',
            name='price',
            field=models.FloatField(default=0),
        ),
    ]
