# Generated by Django 3.2.7 on 2021-09-23 21:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('service_app', '0024_auto_20210923_2152'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='case',
        ),
        migrations.RemoveField(
            model_name='task',
            name='disc',
        ),
        migrations.RemoveField(
            model_name='task',
            name='graphic',
        ),
        migrations.RemoveField(
            model_name='task',
            name='memory',
        ),
        migrations.RemoveField(
            model_name='task',
            name='motherboard',
        ),
        migrations.RemoveField(
            model_name='task',
            name='power_supply',
        ),
        migrations.RemoveField(
            model_name='task',
            name='processor',
        ),
        migrations.AddField(
            model_name='task',
            name='pc',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to='service_app.pc'),
        ),
    ]
