# Generated by Django 3.2.7 on 2021-09-24 18:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('service_app', '0026_alter_task_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pc',
            name='case',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='service_app.case'),
        ),
        migrations.AlterField(
            model_name='pc',
            name='motherboard',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='service_app.motherboard'),
        ),
        migrations.AlterField(
            model_name='pc',
            name='power_supply',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='service_app.powersupply'),
        ),
        migrations.AlterField(
            model_name='pc',
            name='processor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='service_app.processor'),
        ),
    ]
