# Generated by Django 3.2.7 on 2021-09-27 17:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_app', '0027_auto_20210924_2048'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='deadline',
            field=models.DateField(default=datetime.date(2021, 9, 27)),
        ),
    ]
